"""
app.py  --  Healthcare Risk Stratification App
Run with:  streamlit run app.py
Requires:  risk_model.pkl and roc_curve.png (generated by train_model.py)
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.graph_objects as go
import os

st.set_page_config(
    page_title="Healthcare Risk Stratification",
    page_icon="hospital",
    layout="wide",
)

@st.cache_resource
def load_model():
    if not os.path.exists('risk_model.pkl'):
        st.error("Model file 'risk_model.pkl' not found. Run train_model.py first.")
        st.stop()
    return joblib.load('risk_model.pkl')

model = load_model()

def risk_level(prob):
    if prob >= 0.65:
        return "High Risk", "#ff4c4c"
    elif prob >= 0.35:
        return "Moderate Risk", "#f5a623"
    else:
        return "Low Risk", "#4caf50"

def gauge_chart(prob, color):
    fig = go.Figure(go.Indicator(
        mode="gauge+number",
        value=round(prob * 100, 1),
        number={"suffix": "%", "font": {"color": color, "size": 40}},
        gauge={
            "axis": {"range": [0, 100]},
            "bar":  {"color": color, "thickness": 0.3},
            "steps": [
                {"range": [0,  35], "color": "#d4edda"},
                {"range": [35, 65], "color": "#fff3cd"},
                {"range": [65, 100], "color": "#f8d7da"},
            ],
            "threshold": {
                "line": {"color": color, "width": 4},
                "thickness": 0.8,
                "value": round(prob * 100, 1),
            },
        },
        title={"text": "Risk Probability", "font": {"size": 16}},
    ))
    fig.update_layout(height=280, margin=dict(t=40, b=10, l=20, r=20),
                      paper_bgcolor="rgba(0,0,0,0)")
    return fig

def feature_bar_chart(age, los, cost, abnormal_labs, coefs):
    contributions = [abs(coefs[i] * v) for i, v in enumerate([age, los, cost, abnormal_labs])]
    total = sum(contributions) or 1
    labels = ["Age", "Length of stay", "Treatment cost", "Abnormal labs"]
    values = [round(c / total * 100, 1) for c in contributions]
    colors = ["#378ADD", "#f5a623", "#4caf50", "#e24b4a"]

    fig = go.Figure(go.Bar(
        x=values, y=labels, orientation='h',
        marker_color=colors,
        text=[f"{v}%" for v in values],
        textposition='outside',
    ))
    fig.update_layout(
        title="Feature contributions",
        xaxis=dict(range=[0, 115], showgrid=False, visible=False),
        yaxis=dict(showgrid=False),
        height=250,
        margin=dict(t=40, b=10, l=10, r=50),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
    )
    return fig

# UI
st.title("Healthcare Risk Stratification")
st.caption("Predicts risk of complicated outcome or death based on patient data.")
st.divider()

col_inputs, col_results = st.columns([1, 1.4], gap="large")

with col_inputs:
    st.subheader("Patient details")

    age = st.number_input("Age (years)", min_value=0, max_value=120, value=57,
                          help="Patient age in years")
    los = st.number_input("Length of stay (days)", min_value=0, max_value=365, value=15,
                          help="Number of days admitted")
    cost = st.number_input("Treatment cost", min_value=0.0, value=5000.0, step=500.0,
                           help="Total treatment cost")

    st.markdown("**Lab results**")
    blood_sugar = st.number_input("Blood sugar (mg/dL)", min_value=0.0, value=100.0,
                                   help="Abnormal if > 120 mg/dL")
    cholesterol = st.number_input("Cholesterol (mg/dL)", min_value=0.0, value=180.0,
                                   help="Abnormal if > 200 mg/dL")
    hemoglobin  = st.number_input("Hemoglobin (g/dL)",  min_value=0.0, value=14.0,
                                   help="Abnormal if < 13 g/dL")

    abnormal_lab_count = int(
        (blood_sugar > 120) +
        (cholesterol > 200) +
        (hemoglobin  < 13)
    )

    lab_color = "normal" if abnormal_lab_count == 0 else "off" if abnormal_lab_count == 1 else "inverse"
    st.metric("Abnormal lab values", f"{abnormal_lab_count} / 3",
              delta="All normal" if abnormal_lab_count == 0 else f"{abnormal_lab_count} flagged",
              delta_color=lab_color)

    # Input validation
    for msg, cond in [
        ("Age is 0 -- please verify.", age == 0),
        ("Length of stay is 0 -- please verify.", los == 0),
        ("Treatment cost is 0 -- please verify.", cost == 0),
    ]:
        if cond:
            st.warning(f"Warning: {msg}")

    predict_btn = st.button("Predict risk", type="primary", use_container_width=True)

with col_results:
    st.subheader("Prediction results")

    if predict_btn:
        input_df = pd.DataFrame(
            [[age, los, cost, abnormal_lab_count]],
            columns=['Age', 'Lengthofstay', 'TreatmentCost', 'AbnormalLabCount']
        )

        probability = float(model.predict_proba(input_df)[0][1])
        label, color = risk_level(probability)

        st.markdown(
            f"<h2 style='color:{color}; margin-bottom:0'>{label}</h2>"
            f"<p style='color:gray; margin-top:4px'>Probability: "
            f"<strong style='color:{color}'>{probability:.2f}</strong></p>",
            unsafe_allow_html=True,
        )

        st.plotly_chart(gauge_chart(probability, color), use_container_width=True)

        coefs = model.coef_[0]
        st.plotly_chart(
            feature_bar_chart(age, los, cost, abnormal_lab_count, coefs),
            use_container_width=True
        )

        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Age",           f"{age} yrs")
        m2.metric("Stay",          f"{los} days")
        m3.metric("Cost",          f"{cost:,.0f}")
        m4.metric("Abnormal labs", f"{abnormal_lab_count}/3")

    else:
        st.info("Fill in the patient details on the left and click **Predict risk**.")

st.divider()
with st.expander("Model performance -- ROC curve"):
    if os.path.exists("roc_curve.png"):
        st.image("roc_curve.png", caption="Receiver Operating Characteristics", width=500)
    else:
        st.warning("roc_curve.png not found. Run train_model.py to generate it.")

st.divider()
st.caption(
    "Clinical disclaimer: This tool is for decision support only. "
    "Predictions are based on a logistic regression model trained on historical data. "
    "Always apply clinical judgment. Not a substitute for professional medical advice."
)
